### PR TITLE
Issue map upgrades

### PR DESCRIPTION
**Pull request by doublestranded**
Not urgent, but the route issues map display and editing tools have been broken due to the upgrades to Leaflet, ember-leaflet, etc. I made some changes to get them to work and the biggest ones are:

* using the external ember-leaflet-draw at https://www.npmjs.com/package/ember-leaflet-draw. The Transitland version can and should be deprecated, imo. 
* using the most recent version of the newly-published ember-leaflet-polyline. 
* disabling of ember-leaflet-measure tool, at least until it can be upgraded to use ember-leaflet 3 and Leaflet 1.1. This feature is a nice to have, but not critical.

Also, I'm not entirely sure how this will interact with the station maps @irees, especially with any new functionality (I doubt it will). So review at your own convenience. Again, not urgent.

### CODE REVIEW

**Comment by drewda** [comment]
@doublestranded thanks for contributing all these improvements.

A related PR that can be merged as your convenience: https://github.com/transitland/ember-leaflet-draw/pull/2

**Comment by doublestranded** [comment]
I'm adding 1 more thing

**Comment by irees** [comment]
Thank you @doublestranded - the changes work well and I have tested it locally. You may merge when ready.

**Comment by doublestranded** [comment]
Thanks for taking a look, @irees! I'll merge.

**Pull request merged**
